<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        App\Country::query()->truncate();
        DB::table('countries')->truncate();

        $country_data = array(
            ['title' => "Afghanistan", 'slug' => "afghanistan", 'abbrev' => "AF", 'active' => 1],
            ['title' => "Albania", 'slug' => "albania", 'abbrev' => "AL", 'active' => 1],
            ['title' => "Algeria", 'slug' => "algeria", 'abbrev' => "DZ", 'active' => 1],
            ['title' => "American Samoa", 'slug' => "american-samoa", 'abbrev' => "AS", 'active' => 1],
            ['title' => "Andorra", 'slug' => "andorra", 'abbrev' => "AD", 'active' => 1],
            ['title' => "Angola", 'slug' => "angola", 'abbrev' => "AO", 'active' => 1],
            ['title' => "Anguilla", 'slug' => "anguilla", 'abbrev' => "AI", 'active' => 1],
            ['title' => "Antarctica", 'slug' => "antarctica", 'abbrev' => "AQ", 'active' => 1],
            ['title' => "Antigua And Barbuda", 'slug' => "antigua-and-barbuda", 'abbrev' => "AG", 'active' => 1],
            ['title' => "Argentina", 'slug' => "argentina", 'abbrev' => "AR", 'active' => 1],
            ['title' => "Armenia", 'slug' => "armenia", 'abbrev' => "AM", 'active' => 1],
            ['title' => "Aruba", 'slug' => "aruba", 'abbrev' => "AW", 'active' => 1],
            ['title' => "Australia", 'slug' => "australia", 'abbrev' => "AU", 'active' => 1],
            ['title' => "Austria", 'slug' => "austria", 'abbrev' => "AT", 'active' => 1],
            ['title' => "Azerbaijan", 'slug' => "azerbaijan", 'abbrev' => "AZ", 'active' => 1],
            ['title' => "Bahamas", 'slug' => "bahamas", 'abbrev' => "BS", 'active' => 1],
            ['title' => "Bahrain", 'slug' => "bahrain", 'abbrev' => "BH", 'active' => 1],
            ['title' => "Bangladesh", 'slug' => "bangladesh", 'abbrev' => "BD", 'active' => 1],
            ['title' => "Barbados", 'slug' => "barbados", 'abbrev' => "BB", 'active' => 1],
            ['title' => "Belarus", 'slug' => "belarus", 'abbrev' => "BY", 'active' => 1],
            ['title' => "Belgium", 'slug' => "belgium", 'abbrev' => "BE", 'active' => 1],
            ['title' => "Belize", 'slug' => "belize", 'abbrev' => "BZ", 'active' => 1],
            ['title' => "Benin", 'slug' => "benin", 'abbrev' => "BJ", 'active' => 1],
            ['title' => "Bermuda", 'slug' => "bermuda", 'abbrev' => "BM", 'active' => 1],
            ['title' => "Bhutan", 'slug' => "bhutan", 'abbrev' => "BT", 'active' => 1],
            ['title' => "Bolivia", 'slug' => "bolivia", 'abbrev' => "BO", 'active' => 1],
            ['title' => "Bosnia And Herzegovina", 'slug' => "bosnia-and-herzegovina", 'abbrev' => "BA", 'active' => 1],
            ['title' => "Botswana", 'slug' => "botswana", 'abbrev' => "BW", 'active' => 1],
            ['title' => "Bouvet Island", 'slug' => "bouvet-island", 'abbrev' => "BV", 'active' => 1],
            ['title' => "Brazil", 'slug' => "brazil", 'abbrev' => "BR", 'active' => 1],
            ['title' => "British Indian Ocean Territory", 'slug' => "british-indian-ocean-territory", 'abbrev' => "IO", 'active' => 1],
            ['title' => "Brunei Darussalam", 'slug' => "brunei-darussalam", 'abbrev' => "BN", 'active' => 1],
            ['title' => "Bulgaria", 'slug' => "bulgaria", 'abbrev' => "BG", 'active' => 1],
            ['title' => "Burkina Faso", 'slug' => "burkina-faso", 'abbrev' => "BF", 'active' => 1],
            ['title' => "Burundi", 'slug' => "burundi", 'abbrev' => "BI", 'active' => 1],
            ['title' => "Cambodia", 'slug' => "cambodia", 'abbrev' => "KH", 'active' => 1],
            ['title' => "Cameroon", 'slug' => "cameroon", 'abbrev' => "CM", 'active' => 1],
            ['title' => "Canada", 'slug' => "canada", 'abbrev' => "CA", 'active' => 1],
            ['title' => "Cape Verde", 'slug' => "cape-verde", 'abbrev' => "CV", 'active' => 1],
            ['title' => "Cayman Islands", 'slug' => "cayman-islands", 'abbrev' => "KY", 'active' => 1],
            ['title' => "Central African Republic", 'slug' => "central-african-republic", 'abbrev' => "CF", 'active' => 1],
            ['title' => "Chad", 'slug' => "chad", 'abbrev' => "TD", 'active' => 1],
            ['title' => "Chile", 'slug' => "chile", 'abbrev' => "CL", 'active' => 1],
            ['title' => "China", 'slug' => "china", 'abbrev' => "CN", 'active' => 1],
            ['title' => "Christmas Island", 'slug' => "christmas-island", 'abbrev' => "CX", 'active' => 1],
            ['title' => "Cocos (keeling) Islands", 'slug' => "cocos-keeling-islands", 'abbrev' => "CC", 'active' => 1],
            ['title' => "Colombia", 'slug' => "colombia", 'abbrev' => "CO", 'active' => 1],
            ['title' => "Comoros", 'slug' => "comoros", 'abbrev' => "KM", 'active' => 1],
            ['title' => "Congo", 'slug' => "congo", 'abbrev' => "CG", 'active' => 1],
            ['title' => "Congo, The Democratic Republic Of The", 'slug' => "congo-the-democratic-republic-of-the", 'abbrev' => "CD", 'active' => 1],
            ['title' => "Cook Islands", 'slug' => "cook-islands", 'abbrev' => "CK", 'active' => 1],
            ['title' => "Costa Rica", 'slug' => "costa-rica", 'abbrev' => "CR", 'active' => 1],
            ['title' => "Cote D'ivoire", 'slug' => "cote-divoire", 'abbrev' => "CI", 'active' => 1],
            ['title' => "Croatia", 'slug' => "croatia", 'abbrev' => "HR", 'active' => 1],
            ['title' => "Cuba", 'slug' => "cuba", 'abbrev' => "CU", 'active' => 1],
            ['title' => "Cyprus", 'slug' => "cyprus", 'abbrev' => "CY", 'active' => 1],
            ['title' => "Czech Republic", 'slug' => "czech-republic", 'abbrev' => "CZ", 'active' => 1],
            ['title' => "Denmark", 'slug' => "denmark", 'abbrev' => "DK", 'active' => 1],
            ['title' => "Djibouti", 'slug' => "djibouti", 'abbrev' => "DJ", 'active' => 1],
            ['title' => "Dominica", 'slug' => "dominica", 'abbrev' => "DM", 'active' => 1],
            ['title' => "Dominican Republic", 'slug' => "dominican-republic", 'abbrev' => "DO", 'active' => 1],
            ['title' => "East Timor", 'slug' => "east-timor", 'abbrev' => "TP", 'active' => 1],
            ['title' => "Ecuador", 'slug' => "ecuador", 'abbrev' => "EC", 'active' => 1],
            ['title' => "Egypt", 'slug' => "egypt", 'abbrev' => "EG", 'active' => 1],
            ['title' => "El Salvador", 'slug' => "el-salvador", 'abbrev' => "SV", 'active' => 1],
            ['title' => "Equatorial Guinea", 'slug' => "equatorial-guinea", 'abbrev' => "GQ", 'active' => 1],
            ['title' => "Eritrea", 'slug' => "eritrea", 'abbrev' => "ER", 'active' => 1],
            ['title' => "Estonia", 'slug' => "estonia", 'abbrev' => "EE", 'active' => 1],
            ['title' => "Ethiopia", 'slug' => "ethiopia", 'abbrev' => "ET", 'active' => 1],
            ['title' => "Falkland Islands (malvinas)", 'slug' => "falkland-islands-malvinas", 'abbrev' => "FK", 'active' => 1],
            ['title' => "Faroe Islands", 'slug' => "faroe-islands", 'abbrev' => "FO", 'active' => 1],
            ['title' => "Fiji", 'slug' => "fiji", 'abbrev' => "FJ", 'active' => 1],
            ['title' => "Finland", 'slug' => "finland", 'abbrev' => "FI", 'active' => 1],
            ['title' => "France", 'slug' => "france", 'abbrev' => "FR", 'active' => 1],
            ['title' => "French Guiana", 'slug' => "french-guiana", 'abbrev' => "GF", 'active' => 1],
            ['title' => "French Polynesia", 'slug' => "french-polynesia", 'abbrev' => "PF", 'active' => 1],
            ['title' => "French Southern Territories", 'slug' => "french-southern-territories", 'abbrev' => "TF", 'active' => 1],
            ['title' => "Gabon", 'slug' => "gabon", 'abbrev' => "GA", 'active' => 1],
            ['title' => "Gambia", 'slug' => "gambia", 'abbrev' => "GM", 'active' => 1],
            ['title' => "Georgia", 'slug' => "georgia", 'abbrev' => "GE", 'active' => 1],
            ['title' => "Germany", 'slug' => "germany", 'abbrev' => "DE", 'active' => 1],
            ['title' => "Ghana", 'slug' => "ghana", 'abbrev' => "GH", 'active' => 1],
            ['title' => "Gibraltar", 'slug' => "gibraltar", 'abbrev' => "GI", 'active' => 1],
            ['title' => "Greece", 'slug' => "greece", 'abbrev' => "GR", 'active' => 1],
            ['title' => "Greenland", 'slug' => "greenland", 'abbrev' => "GL", 'active' => 1],
            ['title' => "Grenada", 'slug' => "grenada", 'abbrev' => "GD", 'active' => 1],
            ['title' => "Guadeloupe", 'slug' => "guadeloupe", 'abbrev' => "GP", 'active' => 1],
            ['title' => "Guam", 'slug' => "guam", 'abbrev' => "GU", 'active' => 1],
            ['title' => "Guatemala", 'slug' => "guatemala", 'abbrev' => "GT", 'active' => 1],
            ['title' => "Guinea", 'slug' => "guinea", 'abbrev' => "GN", 'active' => 1],
            ['title' => "Guinea-bissau", 'slug' => "guinea-bissau", 'abbrev' => "GW", 'active' => 1],
            ['title' => "Guyana", 'slug' => "guyana", 'abbrev' => "GY", 'active' => 1],
            ['title' => "Haiti", 'slug' => "haiti", 'abbrev' => "HT", 'active' => 1],
            ['title' => "Heard Island And Mcdonald Islands", 'slug' => "heard-island-and-mcdonald-islands", 'abbrev' => "HM", 'active' => 1],
            ['title' => "Holy See (vatican City State)", 'slug' => "holy-see-vatican-city-state", 'abbrev' => "VA", 'active' => 1],
            ['title' => "Honduras", 'slug' => "honduras", 'abbrev' => "HN", 'active' => 1],
            ['title' => "Hong Kong", 'slug' => "hong-kong", 'abbrev' => "HK", 'active' => 1],
            ['title' => "Hungary", 'slug' => "hungary", 'abbrev' => "HU", 'active' => 1],
            ['title' => "Iceland", 'slug' => "iceland", 'abbrev' => "IS", 'active' => 1],
            ['title' => "India", 'slug' => "india", 'abbrev' => "IN", 'active' => 1],
            ['title' => "Indonesia", 'slug' => "indonesia", 'abbrev' => "ID", 'active' => 1],
            ['title' => "Iran, Islamic Republic Of", 'slug' => "iran-islamic-republic-of", 'abbrev' => "IR", 'active' => 1],
            ['title' => "Iraq", 'slug' => "iraq", 'abbrev' => "IQ", 'active' => 1],
            ['title' => "Ireland", 'slug' => "ireland", 'abbrev' => "IE", 'active' => 1],
            ['title' => "Israel", 'slug' => "israel", 'abbrev' => "IL", 'active' => 1],
            ['title' => "Italy", 'slug' => "italy", 'abbrev' => "IT", 'active' => 1],
            ['title' => "Jamaica", 'slug' => "jamaica", 'abbrev' => "JM", 'active' => 1],
            ['title' => "Japan", 'slug' => "japan", 'abbrev' => "JP", 'active' => 1],
            ['title' => "Jordan", 'slug' => "jordan", 'abbrev' => "JO", 'active' => 1],
            ['title' => "Kazakstan", 'slug' => "kazakstan", 'abbrev' => "KZ", 'active' => 1],
            ['title' => "Kenya", 'slug' => "kenya", 'abbrev' => "KE", 'active' => 1],
            ['title' => "Kiribati", 'slug' => "kiribati", 'abbrev' => "KI", 'active' => 1],
            ['title' => "Korea, Democratic People's Republic Of", 'slug' => "korea-democratic-peoples-republic-of", 'abbrev' => "KP", 'active' => 1],
            ['title' => "Korea, Republic Of", 'slug' => "korea-republic-of", 'abbrev' => "KR", 'active' => 1],
            ['title' => "Kosovo", 'slug' => "kosovo", 'abbrev' => "KV", 'active' => 1],
            ['title' => "Kuwait", 'slug' => "kuwait", 'abbrev' => "KW", 'active' => 1],
            ['title' => "Kyrgyzstan", 'slug' => "kyrgyzstan", 'abbrev' => "KG", 'active' => 1],
            ['title' => "Lao People's Democratic Republic", 'slug' => "lao-peoples-democratic-republic", 'abbrev' => "LA", 'active' => 1],
            ['title' => "Latvia", 'slug' => "latvia", 'abbrev' => "LV", 'active' => 1],
            ['title' => "Lebanon", 'slug' => "lebanon", 'abbrev' => "LB", 'active' => 1],
            ['title' => "Lesotho", 'slug' => "lesotho", 'abbrev' => "LS", 'active' => 1],
            ['title' => "Liberia", 'slug' => "liberia", 'abbrev' => "LR", 'active' => 1],
            ['title' => "Libyan Arab Jamahiriya", 'slug' => "libyan-arab-jamahiriya", 'abbrev' => "LY", 'active' => 1],
            ['title' => "Liechtenstein", 'slug' => "liechtenstein", 'abbrev' => "LI", 'active' => 1],
            ['title' => "Lithuania", 'slug' => "lithuania", 'abbrev' => "LT", 'active' => 1],
            ['title' => "Luxembourg", 'slug' => "luxembourg", 'abbrev' => "LU", 'active' => 1],
            ['title' => "Macau", 'slug' => "macau", 'abbrev' => "MO", 'active' => 1],
            ['title' => "Macedonia, The Former Yugoslav Republic Of", 'slug' => "macedonia-the-former-yugoslav-republic-of", 'abbrev' => "MK", 'active' => 1],
            ['title' => "Madagascar", 'slug' => "madagascar", 'abbrev' => "MG", 'active' => 1],
            ['title' => "Malawi", 'slug' => "malawi", 'abbrev' => "MW", 'active' => 1],
            ['title' => "Malaysia", 'slug' => "malaysia", 'abbrev' => "MY", 'active' => 1],
            ['title' => "Maldives", 'slug' => "maldives", 'abbrev' => "MV", 'active' => 1],
            ['title' => "Mali", 'slug' => "mali", 'abbrev' => "ML", 'active' => 1],
            ['title' => "Malta", 'slug' => "malta", 'abbrev' => "MT", 'active' => 1],
            ['title' => "Marshall Islands", 'slug' => "marshall-islands", 'abbrev' => "MH", 'active' => 1],
            ['title' => "Martinique", 'slug' => "martinique", 'abbrev' => "MQ", 'active' => 1],
            ['title' => "Mauritania", 'slug' => "mauritania", 'abbrev' => "MR", 'active' => 1],
            ['title' => "Mauritius", 'slug' => "mauritius", 'abbrev' => "MU", 'active' => 1],
            ['title' => "Mayotte", 'slug' => "mayotte", 'abbrev' => "YT", 'active' => 1],
            ['title' => "Mexico", 'slug' => "mexico", 'abbrev' => "MX", 'active' => 1],
            ['title' => "Micronesia, Federated States Of", 'slug' => "micronesia-federated-states-of", 'abbrev' => "FM", 'active' => 1],
            ['title' => "Moldova, Republic Of", 'slug' => "moldova-republic-of", 'abbrev' => "MD", 'active' => 1],
            ['title' => "Monaco", 'slug' => "monaco", 'abbrev' => "MC", 'active' => 1],
            ['title' => "Mongolia", 'slug' => "mongolia", 'abbrev' => "MN", 'active' => 1],
            ['title' => "Montserrat", 'slug' => "montserrat", 'abbrev' => "MS", 'active' => 1],
            ['title' => "Montenegro", 'slug' => "montenegro", 'abbrev' => "ME", 'active' => 1],
            ['title' => "Morocco", 'slug' => "morocco", 'abbrev' => "MA", 'active' => 1],
            ['title' => "Mozambique", 'slug' => "mozambique", 'abbrev' => "MZ", 'active' => 1],
            ['title' => "Myanmar", 'slug' => "myanmar", 'abbrev' => "MM", 'active' => 1],
            ['title' => "Namibia", 'slug' => "namibia", 'abbrev' => "NA", 'active' => 1],
            ['title' => "Nauru", 'slug' => "nauru", 'abbrev' => "NR", 'active' => 1],
            ['title' => "Nepal", 'slug' => "nepal", 'abbrev' => "NP", 'active' => 1],
            ['title' => "Netherlands", 'slug' => "netherlands", 'abbrev' => "NL", 'active' => 1],
            ['title' => "Netherlands Antilles", 'slug' => "netherlands-antilles", 'abbrev' => "AN", 'active' => 1],
            ['title' => "New Caledonia", 'slug' => "new-caledonia", 'abbrev' => "NC", 'active' => 1],
            ['title' => "New Zealand", 'slug' => "new-zealand", 'abbrev' => "NZ", 'active' => 1],
            ['title' => "Nicaragua", 'slug' => "nicaragua", 'abbrev' => "NI", 'active' => 1],
            ['title' => "Niger", 'slug' => "niger", 'abbrev' => "NE", 'active' => 1],
            ['title' => "Nigeria", 'slug' => "nigeria", 'abbrev' => "NG", 'active' => 1],
            ['title' => "Niue", 'slug' => "niue", 'abbrev' => "NU", 'active' => 1],
            ['title' => "Norfolk Island", 'slug' => "norfolk-island", 'abbrev' => "NF", 'active' => 1],
            ['title' => "Northern Mariana Islands", 'slug' => "northern-mariana-islands", 'abbrev' => "MP", 'active' => 1],
            ['title' => "Norway", 'slug' => "norway", 'abbrev' => "NO", 'active' => 1],
            ['title' => "Oman", 'slug' => "oman", 'abbrev' => "OM", 'active' => 1],
            ['title' => "Pakistan", 'slug' => "pakistan", 'abbrev' => "PK", 'active' => 1],
            ['title' => "Palau", 'slug' => "palau", 'abbrev' => "PW", 'active' => 1],
            ['title' => "Palestinian Territory, Occupied", 'slug' => "palestinian-territory-occupied", 'abbrev' => "PS", 'active' => 1],
            ['title' => "Panama", 'slug' => "panama", 'abbrev' => "PA", 'active' => 1],
            ['title' => "Papua New Guinea", 'slug' => "papua-new-guinea", 'abbrev' => "PG", 'active' => 1],
            ['title' => "Paraguay", 'slug' => "paraguay", 'abbrev' => "PY", 'active' => 1],
            ['title' => "Peru", 'slug' => "peru", 'abbrev' => "PE", 'active' => 1],
            ['title' => "Philippines", 'slug' => "philippines", 'abbrev' => "PH", 'active' => 1],
            ['title' => "Pitcairn", 'slug' => "pitcairn", 'abbrev' => "PN", 'active' => 1],
            ['title' => "Poland", 'slug' => "poland", 'abbrev' => "PL", 'active' => 1],
            ['title' => "Portugal", 'slug' => "portugal", 'abbrev' => "PT", 'active' => 1],
            ['title' => "Puerto Rico", 'slug' => "puerto-rico", 'abbrev' => "PR", 'active' => 1],
            ['title' => "Qatar", 'slug' => "qatar", 'abbrev' => "QA", 'active' => 1],
            ['title' => "Reunion", 'slug' => "reunion", 'abbrev' => "RE", 'active' => 1],
            ['title' => "Romania", 'slug' => "romania", 'abbrev' => "RO", 'active' => 1],
            ['title' => "Russian Federation", 'slug' => "russian-federation", 'abbrev' => "RU", 'active' => 1],
            ['title' => "Rwanda", 'slug' => "rwanda", 'abbrev' => "RW", 'active' => 1],
            ['title' => "Saint Helena", 'slug' => "saint-helena", 'abbrev' => "SH", 'active' => 1],
            ['title' => "Saint Kitts And Nevis", 'slug' => "saint-kitts-and-nevis", 'abbrev' => "KN", 'active' => 1],
            ['title' => "Saint Lucia", 'slug' => "saint-lucia", 'abbrev' => "LC", 'active' => 1],
            ['title' => "Saint Pierre And Miquelon", 'slug' => "saint-pierre-and-miquelon", 'abbrev' => "PM", 'active' => 1],
            ['title' => "Saint Vincent And The Grenadines", 'slug' => "saint-vincent-and-the-grenadines", 'abbrev' => "VC", 'active' => 1],
            ['title' => "Samoa", 'slug' => "samoa", 'abbrev' => "WS", 'active' => 1],
            ['title' => "San Marino", 'slug' => "san-marino", 'abbrev' => "SM", 'active' => 1],
            ['title' => "Sao Tome And Principe", 'slug' => "sao-tome-and-principe", 'abbrev' => "ST", 'active' => 1],
            ['title' => "Saudi Arabia", 'slug' => "saudi-arabia", 'abbrev' => "SA", 'active' => 1],
            ['title' => "Senegal", 'slug' => "senegal", 'abbrev' => "SN", 'active' => 1],
            ['title' => "Serbia", 'slug' => "serbia", 'abbrev' => "RS", 'active' => 1],
            ['title' => "Seychelles", 'slug' => "seychelles", 'abbrev' => "SC", 'active' => 1],
            ['title' => "Sierra Leone", 'slug' => "sierra-leone", 'abbrev' => "SL", 'active' => 1],
            ['title' => "Singapore", 'slug' => "singapore", 'abbrev' => "SG", 'active' => 1],
            ['title' => "Slovakia", 'slug' => "slovakia", 'abbrev' => "SK", 'active' => 1],
            ['title' => "Slovenia", 'slug' => "slovenia", 'abbrev' => "SI", 'active' => 1],
            ['title' => "Solomon Islands", 'slug' => "solomon-islands", 'abbrev' => "SB", 'active' => 1],
            ['title' => "Somalia", 'slug' => "somalia", 'abbrev' => "SO", 'active' => 1],
            ['title' => "South Africa", 'slug' => "south-africa", 'abbrev' => "ZA", 'active' => 1],
            ['title' => "South Georgia And The South Sandwich Islands", 'slug' => "south-georgia-and-the-south-sandwich-islands", 'abbrev' => "GS", 'active' => 1],
            ['title' => "Spain", 'slug' => "spain", 'abbrev' => "ES", 'active' => 1],
            ['title' => "Sri Lanka", 'slug' => "sri-lanka", 'abbrev' => "LK", 'active' => 1],
            ['title' => "Sudan", 'slug' => "sudan", 'abbrev' => "SD", 'active' => 1],
            ['title' => "Suriname", 'slug' => "suriname", 'abbrev' => "SR", 'active' => 1],
            ['title' => "Svalbard And Jan Mayen", 'slug' => "svalbard-and-jan-mayen", 'abbrev' => "SJ", 'active' => 1],
            ['title' => "Swaziland", 'slug' => "swaziland", 'abbrev' => "SZ", 'active' => 1],
            ['title' => "Sweden", 'slug' => "sweden", 'abbrev' => "SE", 'active' => 1],
            ['title' => "Switzerland", 'slug' => "switzerland", 'abbrev' => "CH", 'active' => 1],
            ['title' => "Syrian Arab Republic", 'slug' => "syrian-arab-republic", 'abbrev' => "SY", 'active' => 1],
            ['title' => "Taiwan, Province Of China", 'slug' => "taiwan-province-of-china", 'abbrev' => "TW", 'active' => 1],
            ['title' => "Tajikistan", 'slug' => "tajikistan", 'abbrev' => "TJ", 'active' => 1],
            ['title' => "Tanzania, United Republic Of", 'slug' => "tanzania-united-republic-of", 'abbrev' => "TZ", 'active' => 1],
            ['title' => "Thailand", 'slug' => "thailand", 'abbrev' => "TH", 'active' => 1],
            ['title' => "Togo", 'slug' => "togo", 'abbrev' => "TG", 'active' => 1],
            ['title' => "Tokelau", 'slug' => "tokelau", 'abbrev' => "TK", 'active' => 1],
            ['title' => "Tonga", 'slug' => "tonga", 'abbrev' => "TO", 'active' => 1],
            ['title' => "Trinidad And Tobago", 'slug' => "trinidad-and-tobago", 'abbrev' => "TT", 'active' => 1],
            ['title' => "Tunisia", 'slug' => "tunisia", 'abbrev' => "TN", 'active' => 1],
            ['title' => "Turkey", 'slug' => "turkey", 'abbrev' => "TR", 'active' => 1],
            ['title' => "Turkmenistan", 'slug' => "turkmenistan", 'abbrev' => "TM", 'active' => 1],
            ['title' => "Turks And Caicos Islands", 'slug' => "turks-and-caicos-islands", 'abbrev' => "TC", 'active' => 1],
            ['title' => "Tuvalu", 'slug' => "tuvalu", 'abbrev' => "TV", 'active' => 1],
            ['title' => "Uganda", 'slug' => "uganda", 'abbrev' => "UG", 'active' => 1],
            ['title' => "Ukraine", 'slug' => "ukraine", 'abbrev' => "UA", 'active' => 1],
            ['title' => "United Arab Emirates", 'slug' => "united-arab-emirates", 'abbrev' => "AE", 'active' => 1],
            ['title' => "United Kingdom", 'slug' => "united-kingdom", 'abbrev' => "GB", 'active' => 1],
            ['title' => "United States", 'slug' => "united-states", 'abbrev' => "US", 'active' => 1],
            ['title' => "United States Minor Outlying Islands", 'slug' => "united-states-minor-outlying-islands", 'abbrev' => "UM", 'active' => 1],
            ['title' => "Uruguay", 'slug' => "uruguay", 'abbrev' => "UY", 'active' => 1],
            ['title' => "Uzbekistan", 'slug' => "uzbekistan", 'abbrev' => "UZ", 'active' => 1],
            ['title' => "Vanuatu", 'slug' => "vanuatu", 'abbrev' => "VU", 'active' => 1],
            ['title' => "Venezuela", 'slug' => "venezuela", 'abbrev' => "VE", 'active' => 1],
            ['title' => "Viet Nam", 'slug' => "viet-nam", 'abbrev' => "VN", 'active' => 1],
            ['title' => "Virgin Islands, British", 'slug' => "virgin-islands-british", 'abbrev' => "VG", 'active' => 1],
            ['title' => "Virgin Islands, U.s.", 'slug' => "virgin-islands-u-s", 'abbrev' => "VI", 'active' => 1],
            ['title' => "Wallis And Futuna", 'slug' => "wallis-and-futuna", 'abbrev' => "WF", 'active' => 1],
            ['title' => "Western Sahara", 'slug' => "western-sahara", 'abbrev' => "EH", 'active' => 1],
            ['title' => "Yemen", 'slug' => "yemen", 'abbrev' => "YE", 'active' => 1],
            ['title' => "Zambia", 'slug' => "zambia", 'abbrev' => "ZM", 'active' => 1],
            ['title' => "Zimbabwe", 'slug' => "zimbabwe", 'abbrev' => "ZW", 'active' => 1],
            ['title' => "Nathan Town", 'slug' => "nathan-town", 'abbrev' => "NT", 'active' => 0]
        );

        DB::table('countries')->insert($country_data);
    }
}